### ISSUE TITLE
在未登入时候测试点赞或者收藏的时候会出现不能跳转请登入页面的概率问题,点击收藏或者点赞btn 时候有两次的alert()事件以及页面重新刷新的动作

### ISSUE THREAD

**Issue by 734311568** [Redandan/redan-web-test#10]
`
页面加载查询是否点赞动作
$(document).ready(function () {

        $(".fa-heartlike").each(function () {

                var val = $(this).attr("mark");

                var stoty = $(this).parent().siblings('input[name="story"]').val();
                var who = $(this).parent().siblings('input[name="who"]').val();

                $(this).addClass("fa-heartlike" + val);
                if (stoty !== null &&stoty !== ""&&who !== null&& who !== "") {
                $.get("/like", {'story': stoty, 'who': who}, function (data) {
                        // alert("返回什么"+data);
                        if ("You don't have required role to perform this action." !== data) {

                                if (data === "已收点赞") {

                                        $(".fa-heartlike" + val).addClass("fas");

                                }
                                if (data === "取消点赞") {

                                        $(".fa-heartlike" + val).addClass("far");

                                }
                        }
                }, 'text');
                }
        });

});

================分割线===============================
这里是页面加载查询时候

/* 
 * 加载收藏 
 * 

 */
$(document).ready(function () {

        $(".fa-bookmarkee").each(function () {

                var val = $(this).attr("mark");

                var stoty = $(this).parent().siblings('input[name="story"]').val();
                var who = $(this).parent().siblings('input[name="who"]').val();

                $(this).addClass("fa-bookmarkee" + val);
                  if (stoty !== null &&stoty !== ""&&who !== null&& who !== "") {
                $.get("/bookmark", {'story': stoty, 'who': who}, function (data) {
                        // alert("返回什么"+data);
                        if ("You don't have required role to perform this action." !== data) {

                                if (data === "已收藏") {

                                        $(".fa-bookmarkee" + val).addClass("fas");

                                }
                                if (data === "没有收藏") {

                                        $(".fa-bookmarkee" + val).addClass("far");

                                }
                        }
                }, 'text');
                  }
        });

});

`

**Comment by yuchiahui** [comment]
因為首頁載入memberCenter.js，location.reload()會導致頁面重載
	$("FORM[method='POST']").submit(function (e) {
		...
		$.post($(this).attr("action"), $(this).serialize(), function (data) {
			alert(data);
			location.reload();
		}, "text");
	});
首頁移除memberCenter.js後已正常，程式碼已push

**Comment by 734311568** [comment]
收到




------------------ 原始邮件 ------------------
发件人: "家惠"<notifications@github.com>; 
发送时间: 2019年5月20日(星期一) 中午12:26
收件人: "Redandan/redan-web-test"<redan-web-test@noreply.github.com>; 
抄送: "5454wf"<734311568@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Redandan/redan-web-test] 在未登入时候测试点赞或者收藏的时候会出现不能跳转请登入页面的概率问题,点击收藏或者点赞btn 时候有两次的alert()事件以及页面重新刷新的动作 (#10)




因為首頁載入memberCenter.js，location.reload()會導致頁面重載
 $("FORM[method='POST']").submit(function (e) {
 ...
 $.post($(this).attr("action"), $(this).serialize(), function (data) {
 alert(data);
 location.reload();
 }, "text");
 });
 首頁移除memberCenter.js後已正常，程式碼已push
