### ISSUE TITLE
邮箱无法激活

### ISSUE THREAD

**Issue by 2662729661** [Redandan/redan-web-test#3]
1.账号注册后,进入邮箱激活,不确定是无法激活还是无法进入激活页面.
2.未激活账号,不建议跳转注册页面,建议弹框(请前往邮箱激活账号)

**Comment by Redandan** [comment]
1.應該是大陸會擋gmail 
2.我會去修正

**Comment by Redandan** [comment]
剛才惠姐試了一下如果是Localhost:8080的話才會擋,其它的URL 可以正常
